<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Ydrus\LeonardoAI\Endpoint;

class GetTextureGenerationsByModelId extends \Ydrus\LeonardoAI\Runtime\Client\BaseEndpoint implements \Ydrus\LeonardoAI\Runtime\Client\Endpoint
{
    use \Ydrus\LeonardoAI\Runtime\Client\EndpointTrait;
    protected $modelId;

    /**
     * This endpoint gets the specific texture generations by the 3d model id.
     *
     * @param string $modelId         _"modelId" is required (enter it either in parameters or request body)_
     * @param array  $queryParameters {
     *
     * @var int $offset
     * @var int $limit
     *          }
     */
    public function __construct(string $modelId, ?\Ydrus\LeonardoAI\Model\GenerationsTextureModelModelIdGetBody $requestBody = null, array $queryParameters = [])
    {
        $this->modelId = $modelId;
        $this->body = $requestBody;
        $this->queryParameters = $queryParameters;
    }

    public function getMethod(): string
    {
        return 'GET';
    }

    public function getUri(): string
    {
        return str_replace(['{modelId}'], [$this->modelId], '/generations-texture/model/{modelId}');
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        if ($this->body instanceof \Ydrus\LeonardoAI\Model\GenerationsTextureModelModelIdGetBody) {
            return [['Content-Type' => ['application/json']], $serializer->serialize($this->body, 'json')];
        }

        return [[], null];
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    protected function getQueryOptionsResolver(): \Symfony\Component\OptionsResolver\OptionsResolver
    {
        $optionsResolver = parent::getQueryOptionsResolver();
        $optionsResolver->setDefined(['offset', 'limit']);
        $optionsResolver->setRequired([]);
        $optionsResolver->setDefaults(['offset' => 0, 'limit' => 10]);
        $optionsResolver->addAllowedTypes('offset', ['int']);
        $optionsResolver->addAllowedTypes('limit', ['int']);

        return $optionsResolver;
    }

    /**
     * @return \Ydrus\LeonardoAI\Model\GenerationsTextureModelModelIdGetResponse200|null
     */
    protected function transformResponseBody(\Psr\Http\Message\ResponseInterface $response, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if (is_null($contentType) === false && (200 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            return $serializer->deserialize($body, 'Ydrus\LeonardoAI\Model\GenerationsTextureModelModelIdGetResponse200', 'json');
        }
    }

    public function getAuthenticationScopes(): array
    {
        return ['bearerAuth'];
    }
}
