<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace LeonardoAI\Endpoint;

class UploadDatasetImageFromGen extends \LeonardoAI\Runtime\Client\BaseEndpoint implements \LeonardoAI\Runtime\Client\Endpoint
{
    use \LeonardoAI\Runtime\Client\EndpointTrait;
    protected $datasetId;

    /**
     * This endpoint will upload a previously generated image to the dataset.
     *
     * @param string $datasetId the ID of the dataset to upload the image to
     */
    public function __construct(string $datasetId, \LeonardoAI\Model\DatasetsDatasetIdUploadGenPostBody $requestBody)
    {
        $this->datasetId = $datasetId;
        $this->body = $requestBody;
    }

    public function getMethod(): string
    {
        return 'POST';
    }

    public function getUri(): string
    {
        return str_replace(['{datasetId}'], [$this->datasetId], '/datasets/{datasetId}/upload/gen');
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        if ($this->body instanceof \LeonardoAI\Model\DatasetsDatasetIdUploadGenPostBody) {
            return [['Content-Type' => ['application/json']], $serializer->serialize($this->body, 'json')];
        }

        return [[], null];
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    /**
     * @return \LeonardoAI\Model\DatasetsDatasetIdUploadGenPostResponse200|null
     */
    protected function transformResponseBody(\Psr\Http\Message\ResponseInterface $response, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        $status = $response->getStatusCode();
        $body = (string) $response->getBody();
        if (is_null($contentType) === false && (200 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            return $serializer->deserialize($body, 'LeonardoAI\Model\DatasetsDatasetIdUploadGenPostResponse200', 'json');
        }
    }

    public function getAuthenticationScopes(): array
    {
        return ['bearerAuth'];
    }
}
