<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace LeonardoAI\Model;

class UserElementInput extends \ArrayObject
{
    /**
     * @var array
     */
    protected $initialized = [];

    public function isInitialized($property): bool
    {
        return array_key_exists($property, $this->initialized);
    }
    /**
     * Unique identifier for user element.
     *
     * @var int|null
     */
    protected $userLoraId;
    /**
     * Weight for the element.
     *
     * @var float|null
     */
    protected $weight;

    /**
     * Unique identifier for user element.
     */
    public function getUserLoraId(): ?int
    {
        return $this->userLoraId;
    }

    /**
     * Unique identifier for user element.
     */
    public function setUserLoraId(?int $userLoraId): self
    {
        $this->initialized['userLoraId'] = true;
        $this->userLoraId = $userLoraId;

        return $this;
    }

    /**
     * Weight for the element.
     */
    public function getWeight(): ?float
    {
        return $this->weight;
    }

    /**
     * Weight for the element.
     */
    public function setWeight(?float $weight): self
    {
        $this->initialized['weight'] = true;
        $this->weight = $weight;

        return $this;
    }
}
